### ISSUE TITLE
OSError for EclKW.read_grdecl

### ISSUE THREAD

**Issue by trhallam** [equinor/resdata#604] opened 2019-04-02 17:00 UTC
Hiya,

I'm having some trouble with reading grdecl files. I'm using Python 3.6, llibecl 2.4, Windows 10 x64.

Currently I get the following output.
```
>>> from ecl.grid import EclGrid
>>> grid = EclGrid.load_from_grdecl('test_data/TS2N/F/TS2N.GRDECL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\site-packages\ecl\grid\ecl_grid.py", line 152, in load_from_grdecl
    specgrid = EclKW.read_grdecl(f, "SPECGRID", ecl_type=EclDataType.ECL_INT, strict=False)
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\site-packages\ecl\eclfile\ecl_kw.py", line 309, in read_grdecl
    return cls._load_grdecl(cfile, kw, strict, ecl_type)
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\site-packages\cwrap\prototype.py", line 217, in __call__
    return self._func(*args)
OSError: exception: access violation writing 0x0000000000000024
```

I've checked the GRDECL file and SPECGRID is present along with ZCORN and COORD which I note are also required from (`ecl_grid.py` docs).  This is the header of the file
```
NOECHO
PINCH
/
MAPUNITS
 'FEET    '
/
MAPAXES
   0.18692001E+07  -0.18975500E+06   0.18692001E+07  -0.18965500E+06
   0.18693001E+07  -0.18965500E+06
/
GRIDUNIT
 'FEET    ' '        '
/
SPECGRID
11 11 5 1 F
/
COORD
   0.46586250E+04  -0.55005786E+04   0.49489307E+04   0.46586250E+04
  -0.55005786E+04   0.49989307E+04
...
```

I've also tried commenting out the first line here but the same error occurs on the `ZCORN` keyword.
https://github.com/equinor/libecl/blob/5a62567956c3266faa2eb36b5cf7808bed9e1ce0/python/ecl/grid/ecl_grid.py#L152-L154

**Comment by markusdregi** [comment] 2019-04-02 18:04
Hi @trhallam and thanks for reporting this issue!

Unfortunately, Windows (and even more so Windows and Python 3) is an environment that _libecl_ is not that often exposed to. There was not much information in the stacktrace you provided. Would it be possible for you to provide a complete input file that reproduces this error?

Cheers,
Markus

**Comment by trhallam** [comment] 2019-04-02 18:17
Had to rename to txt but this is the file. 

Understand that I'm using an obscure environment. Would compiling with the debug flag enable a better trace? It really just stops after reaching cwrap and it calls

https://github.com/equinor/libecl/blob/5a62567956c3266faa2eb36b5cf7808bed9e1ce0/python/ecl/eclfile/ecl_kw.py#L103

and 

https://github.com/equinor/cwrap/blob/afeaa888959151ce4f256f70f357e8ef7a1098b3/cwrap/prototype.py#L208-L217

[TS2.txt](https://github.com/equinor/libecl/files/3035331/TS2.txt)

**Comment by markusdregi** [comment] 2019-04-02 18:24
Thank you for the data. Let me have a look at this tomorrow and then get back to you 👍

**Comment by trhallam** [comment] 2019-04-13 16:16
Hi @markusdregi  I know you guys are busy but wondering if you managed to test my data on your end?
Cheers

**Comment by trhallam** [comment] 2020-12-02 10:26
@crayxt , I forgot about this error. Mainly I just read the binary outputs from Eclipse now. It is relatively straightforward to build a parser for these files in Python so understand that it's not high priority.

**Comment by crayxt** [comment] 2020-12-02 11:00
>  It is relatively straightforward to build a parser for these files in Python so understand that it's not high priority.

Exactly the way I solved this issue, although I had a toy parser for that already.

**Comment by eivindjahren** [comment] 2024-08-06 06:07
Attempted to reproduce this error with:

```
NOECHO
PINCH
/
MAPUNITS
 'FEET    '
/
MAPAXES
   0.18692001E+07  -0.18975500E+06   0.18692001E+07  -0.18965500E+06
   0.18693001E+07  -0.18965500E+06
/
GRIDUNIT
 'FEET    ' '        '
/
SPECGRID
3 3 3 1 F
/
COORD
   0.46586250E+04  -0.55005786E+04   0.49489307E+04   0.46586250E+04
  -0.55005786E+04   0.49989307E+04   -0.55005786E+04  -0.55005786E+04
  -0.55005786E+04
/
ZCORN
   0.46586250E+04  -0.55005786E+04   0.49489307E+04   0.46586250E+04
  -0.55005786E+04   0.49989307E+04   -0.55005786E+04  -0.55005786E+04
  -0.55005786E+04 0.46586250E+04  -0.55005786E+04   0.49489307E+04
  0.46586250E+04 -0.55005786E+04   0.49989307E+04   -0.55005786E+04
  -0.55005786E+04 -0.55005786E+04 0.46586250E+04  -0.55005786E+04
  0.49489307E+04   0.46586250E+04 -0.55005786E+04   0.49989307E+04
  -0.55005786E+04  -0.55005786E+04 -0.55005786E+04
/

ZCORN
    1 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1
/
```

Seems like this issue has either been resolved or is due to some data in the file that was not reported or the environment. Closing this as cannot reproduce for now.

**Closed by eivindjahren** 2024-08-06 06:07 UTC
Labels: bug
