### ISSUE TITLE
Clean up deprecations

### ISSUE THREAD

**Issue by mortalisk** [equinor/resdata#717] opened 2020-06-25 07:02 UTC
As part of equinor/ert/issues/737 Let's try to remove as many deprecated pieces of code as possible. Here is a list.

**Runtime warnings:**

- ecl/__init__.py
  - line 15 Importing from ert.ecl, ecl.ecl or ert is deprecated
- eclfile/ecl_file.py  (1 usage found)
  - line 709 openEclFile is deprecated for 3 years
- eclfile/ecl_kw.py
  - line 57 EclTypeEnum is deprecated for 3 years
  - line 971 property type is deprecated for 2 years
  - line 987 EclTypeEnum is deprecated for 3 years
- python/ecl/grid/ecl_grid.py
  - line 212 EclGrid.createRectangular is deprecated 3 years
- python/ecl/summary/ecl_sum.py
  - line 320 get_vector has been deprecated 2 years
  - line 373 get_values has been deprecated 2 years
  - line 637 get_last_value is deprecated 2 years
  - line 1115 mpl_dates property has been deprecated 2 years
  - line 1129 get_mpl_dates has been deprecated 2 years
- python/ecl/summary/ecl_sum_vector.py
  - line 106 mpl_dates deprecated 1.5 years
- python/ecl/util/util/__init__.py
  - line 113 monkey_the_camel, is used all over to confuse your IDE (and to deprecate camel cased methods). Enough swallowing of camels.. Let's stop monkeying around. Probably time to nip that camel in it's monkey bud!
- python/ert/ecl/__init__.py  (1 usage found)
  - line 32 Importing from ert.ecl, ecl.ecl or ert is deprecated

**Other deprecations:**

- CMakeLists.txt
  - line 111 BUILD_PYTHON is deprecated
- python/docs/latex/titlesec.sty
  - has some deprecated somethings, is file in use?
- lib/ecl/ecl_file.cpp
  - line 466 ecl_file_get_active_view is Very deprecated, but seems to be used many places, can it be replaced?
  - line 883 ecl_file_push_block is DEPRECATED and seems to not be in use
- lib/include/ert/ecl/ecl_file.hpp
  - line 119 lists some functions as deprecated since at least 4 years:
    - ecl_file_push_block, ecl_file_pop_block, ecl_file_subselect_block, ecl_file_select_block, ecl_file_open_rstblock_sim_time, ecl_file_open_rstblock_report_step, ecl_file_iopen_rstblock seems to not be used directly
    - ecl_file_select_rstblock_sim_time seems to be used, but only by other unused functions
    - ecl_file_select_rstblock_report_step, ecl_file_iselect_rstblock,  is in use at least by the program run_gravity
- lib/include/ert/ecl_well/well_const.hpp
  - line 135+ lists some enums as deprecated, and seem not to be in use:
    - ERT_UNDOCUMENTED_ZERO, ERT_PRODUCER, ERT_OIL_INJECTOR, ERT_WATER_INJECTOR, ERT_GAS_INJECTOR
- lib/include/ert/util/buffer_string.h  (1 usage found)
  - everything is deprecated, and it seems none of the functions are in use, except by other unused functions
- python/ecl/rft/ecl_rft_cell.py  (1 usage found)
  - line 30 mentions some deprecated properties that don't seem to exist anymore
- python/ecl/util/util/lookup_table.py  (1 usage found)
  - line 73 mentions some Deprecated properties, presumably the 4 next properties, which has been deprecated for 6 years

**Comment by abingham** [comment] 2022-12-07 09:40
I'd like to upvote this if that's a thing on this project. In particular, ecl_grid.py uses the deprecated `EclKW.type` property, resulting in a lot of warnings printed to the terminal. I'm using ecl to develop some command line tools, and this extra chatter is confusing to users.

**Comment by pinkwah** [comment] 2023-12-18 11:41
Duplicate of https://github.com/equinor/resdata/issues/537

**Closed by pinkwah** 2023-12-18 11:41 UTC
